server:
  port: 8090


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # Example for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: ${PSQL_USER_NAME}
    password: ${PSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
    dlq-topic: sample-dlq-topic
    communication-topic: communication-topic
    communication-group-id: communication-group-id
    communication-partitioned-topic: communication-partitioned-topic
    communication-partitioned-group-id: communication-partitioned-group-id
    communication-dlq-group-id: communication-dlq-group-id
    no-of-partitions: 10
    retry:
      backoff:
        interval: 500
        max-attempts: 3



