

spring:
  config:
    import:
      - classpath:dev/kafka.yml
      - classpath:dev/health-check.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # Example for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: ${PSQL_USER_NAME}
    password: ${PSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}




