server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Example for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: ${PSQL_USER_NAME}
    password: ${PSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}


